// Command regenerate rebuilds darkwing's conformance corpus from a DuckDB
// source tree and the pinned DuckDB CLI binary: it extracts every SQL
// statement from test/sql/**/*.test and test/fuzzer/**/*.test, asks the
// pinned binary for an accept/reject verdict (Parser Error => reject;
// success or any post-parse error => accept), and writes the meyer-style
// corpus under parser/testdata/corpus/. Expected outputs are never edited
// by hand — rerun this command instead.
//
// Usage:
//
//	regenerate -duckdb-src /path/to/duckdb [-binary /path/to/duckdb-cli]
//	           [-out parser/testdata] [-j 8] [-only substring] [-limit N]
package main

import (
	"flag"
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/sqlc-dev/darkwing/internal/duckdbsrc"
	"github.com/sqlc-dev/darkwing/internal/sqltest"
	"github.com/sqlc-dev/darkwing/internal/testfile"
)

// maxStatementLen bounds one corpus statement; fuzzer inputs can be huge
// and add nothing past this size.
const maxStatementLen = 32 * 1024

func main() {
	log.SetFlags(0)
	srcDir := flag.String("duckdb-src", "", "path to a DuckDB source tree at the pinned commit (required)")
	binary := flag.String("binary", "", "pinned DuckDB CLI binary (default: $DARKWING_DUCKDB or duckdb on PATH)")
	outDir := flag.String("out", "parser/testdata", "output directory")
	workers := flag.Int("j", runtime.NumCPU()*2, "oracle worker processes")
	timeout := flag.Duration("timeout", 5*time.Second, "per-statement oracle timeout")
	only := flag.String("only", "", "only regenerate source files whose path contains this substring")
	limit := flag.Int("limit", 0, "stop after this many unique statements (0 = no limit)")
	flag.Parse()

	if *srcDir == "" {
		flag.Usage()
		os.Exit(2)
	}
	if err := run(*srcDir, *binary, *outDir, *workers, *timeout, *only, *limit); err != nil {
		log.Fatalf("error: %v", err)
	}
}

type fileStatements struct {
	// rel is the corpus-relative path (e.g. "sql/select/foo.test").
	rel   string
	stmts []string
}

func run(srcDir, binary, outDir string, workers int, timeout time.Duration, only string, limit int) error {
	if binary == "" {
		b, err := duckdbsrc.Find()
		if err != nil {
			return err
		}
		binary = b
	} else if err := duckdbsrc.Verify(binary); err != nil {
		return err
	}

	files, err := collectFiles(srcDir, only)
	if err != nil {
		return err
	}
	log.Printf("extracting from %d .test files", len(files))

	var perFile []fileStatements
	seen := make(map[string]bool)
	extracted, skippedUnstorable, skippedDot, skippedLong, duplicates := 0, 0, 0, 0, 0
	for _, path := range files {
		stmts, err := sqltest.ExtractFile(path)
		if err != nil {
			return fmt.Errorf("extracting %s: %w", path, err)
		}
		rel, err := filepath.Rel(filepath.Join(srcDir, "test"), path)
		if err != nil {
			return err
		}
		var kept []string
		for _, stmt := range stmts {
			extracted++
			sql := stmt.SQL
			switch {
			case len(sql) > maxStatementLen:
				skippedLong++
			case !testfile.CanStore(sql):
				skippedUnstorable++
			case hasDotCommandLine(sql):
				skippedDot++
			case seen[sql]:
				duplicates++
			default:
				seen[sql] = true
				kept = append(kept, sql)
			}
			if limit > 0 && len(seen) >= limit {
				break
			}
		}
		if len(kept) > 0 {
			perFile = append(perFile, fileStatements{rel: filepath.ToSlash(rel), stmts: kept})
		}
		if limit > 0 && len(seen) >= limit {
			break
		}
	}
	log.Printf("extracted %d statements: %d unique kept, %d duplicates, %d unstorable, %d dot-prefixed, %d oversized",
		extracted, len(seen), duplicates, skippedUnstorable, skippedDot, skippedLong)

	verdicts, err := runOracle(binary, timeout, workers, perFile)
	if err != nil {
		return err
	}

	corpusDir := filepath.Join(outDir, "corpus")
	accepted, rejected := 0, 0
	for _, pf := range perFile {
		out := testfile.File{
			Header: []string{
				"source: test/" + pf.rel,
				"pin: " + duckdbsrc.PinnedCommit,
				"oracle: " + duckdbsrc.PinnedVersion,
				"generated by cmd/regenerate - do not edit",
			},
		}
		for _, sql := range pf.stmts {
			v := verdicts[sql]
			c := testfile.Case{SQL: sql, Reject: v.Reject, Error: v.Error}
			if v.Reject {
				rejected++
			} else {
				accepted++
			}
			out.Cases = append(out.Cases, c)
		}
		dest := filepath.Join(corpusDir, filepath.FromSlash(pf.rel))
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return err
		}
		if err := testfile.Write(dest, &out); err != nil {
			return err
		}
	}
	log.Printf("corpus written: %d files, %d must-accept, %d must-reject", len(perFile), accepted, rejected)

	readme := fmt.Sprintf(`# darkwing conformance corpus

Generated by cmd/regenerate - do not edit corpus files or expectations by
hand; rerun the tool instead (see PLAN.md, § Conformance oracle and corpus).

- Source: DuckDB test/sql/**/*.test and test/fuzzer/**/*.test
- Pinned commit: %s
- Oracle: DuckDB CLI %s (nightly build of the pinned commit)
- Files: %d, cases: %d (%d must-accept, %d must-reject)

Classification: the oracle runs each statement against :memory: with
extension autoloading disabled. An error starting with "Parser Error"
means must-reject (first error line recorded); success or any post-parse
error (Binder, Catalog, ...) means must-accept.

Sidecar files (*.metadata.json) carry todo/skip lists keyed by case
content hash; they are maintained by hand and survive regeneration.
`, duckdbsrc.PinnedCommit, duckdbsrc.PinnedVersion, len(perFile), accepted+rejected, accepted, rejected)
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(outDir, "README.md"), []byte(readme), 0o644)
}

func collectFiles(srcDir, only string) ([]string, error) {
	var files []string
	for _, root := range []string{
		filepath.Join(srcDir, "test", "sql"),
		filepath.Join(srcDir, "test", "fuzzer"),
	} {
		err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() || !strings.HasSuffix(path, ".test") {
				return nil
			}
			if only != "" && !strings.Contains(path, only) {
				return nil
			}
			files = append(files, path)
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	sort.Strings(files)
	return files, nil
}

// hasDotCommandLine reports whether any line could be taken for a CLI dot
// command when fed to the oracle (the CLI interprets a leading '.' at a
// statement boundary).
func hasDotCommandLine(sql string) bool {
	for _, line := range strings.Split(sql, "\n") {
		if strings.HasPrefix(line, ".") {
			return true
		}
	}
	return false
}

func runOracle(binary string, timeout time.Duration, workers int, perFile []fileStatements) (map[string]duckdbsrc.Verdict, error) {
	var all []string
	for _, pf := range perFile {
		all = append(all, pf.stmts...)
	}
	log.Printf("running oracle (%s) over %d statements with %d workers", binary, len(all), workers)

	scratch, err := os.MkdirTemp("", "darkwing-oracle-*")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(scratch)

	type result struct {
		sql string
		v   duckdbsrc.Verdict
		err error
	}
	jobs := make(chan string)
	results := make(chan result)
	var wg sync.WaitGroup
	for i := 0; i < workers; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			oracle := &duckdbsrc.Oracle{Binary: binary, Timeout: timeout, Dir: scratch}
			for sql := range jobs {
				v, err := oracle.Run(sql)
				results <- result{sql: sql, v: v, err: err}
			}
		}()
	}
	go func() {
		for _, sql := range all {
			jobs <- sql
		}
		close(jobs)
		wg.Wait()
		close(results)
	}()

	verdicts := make(map[string]duckdbsrc.Verdict, len(all))
	start := time.Now()
	done, timeouts, crashes := 0, 0, 0
	for r := range results {
		if r.err != nil {
			return nil, r.err
		}
		verdicts[r.sql] = r.v
		if r.v.TimedOut {
			timeouts++
		}
		if r.v.Crashed {
			crashes++
		}
		done++
		if done%5000 == 0 {
			elapsed := time.Since(start)
			log.Printf("  %d/%d (%.0f/s, %d timeouts, %d crashes)",
				done, len(all), float64(done)/elapsed.Seconds(), timeouts, crashes)
		}
	}
	log.Printf("oracle done: %d statements in %s (%d timeouts, %d crashes)",
		done, time.Since(start).Round(time.Second), timeouts, crashes)
	return verdicts, nil
}
