// Corpus conformance harness: darkwing must accept a statement iff the
// pinned DuckDB binary parses it. Corpus files and expectations under
// testdata/ are generated by cmd/regenerate and never edited by hand;
// per-file *.metadata.json sidecars carry todo/skip lists (see
// cmd/next-test for picking the next todo case).
//
// Since milestone 3 the classification runs the full Parse pipeline, so
// transformer-raised rejects (chained comparisons, recursive CTE
// restrictions, ...) count alongside the engine's syntax errors. Since
// milestone 5 every statement has a transformer; remaining todo entries
// cover oracle rejects raised outside the parse pipeline (bind-time
// validation, nested SQL parsing).
package parser

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sqlc-dev/darkwing/internal/matcher"
	"github.com/sqlc-dev/darkwing/internal/testfile"
	"github.com/sqlc-dev/darkwing/lexer"
)

var (
	checkParse  = flag.String("check-parse", "", "dump tokens and parse detail for corpus cases whose SQL contains this substring")
	recordTodos = flag.String("record-todos", "", "triage mode: record oracle disagreements as todo entries with this note instead of failing")
)

// verdict is darkwing's accept/reject classification of one statement,
// mirroring the oracle's: tokenizer errors, matcher syntax errors and
// transformer-raised parser errors are rejects; anything else is an
// accept (ErrUnsupported is kept in the accept path for compatibility,
// though Parse no longer returns it).
type verdict struct {
	reject bool
	detail string
}

func classify(engine *matcher.Engine, sql string) (v verdict) {
	defer func() {
		if r := recover(); r != nil {
			v = verdict{reject: false, detail: fmt.Sprintf("transformer panic: %v", r)}
		}
	}()
	_, err := Parse(context.Background(), strings.NewReader(sql))
	switch {
	case err == nil:
		return verdict{}
	case errors.Is(err, ErrUnsupported):
		return verdict{}
	default:
		var pe *Error
		if errors.As(err, &pe) {
			return verdict{reject: true, detail: pe.Error()}
		}
		// internal errors are neither accept nor reject; surface them
		return verdict{reject: false, detail: "internal error: " + err.Error()}
	}
}

func corpusFiles(t *testing.T) []string {
	t.Helper()
	var files []string
	root := filepath.Join("testdata", "corpus")
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".test") {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walking corpus: %v (run cmd/regenerate first)", err)
	}
	if len(files) == 0 {
		t.Skip("no corpus files under testdata/corpus (run cmd/regenerate)")
	}
	return files
}

func TestCorpus(t *testing.T) {
	engine, err := matcher.Default()
	if err != nil {
		t.Fatal(err)
	}
	_ = engine
	for _, path := range corpusFiles(t) {
		rel, _ := filepath.Rel("testdata", path)
		t.Run(filepath.ToSlash(rel), func(t *testing.T) {
			t.Parallel()
			file, err := testfile.Read(path)
			if err != nil {
				t.Fatal(err)
			}
			meta, err := testfile.ReadMetadata(path)
			if err != nil {
				t.Fatal(err)
			}
			metaDirty := false
			for i := range file.Cases {
				c := &file.Cases[i]
				key := c.Key()
				if _, skip := meta.Skip[key]; skip {
					continue
				}
				got := classify(engine, c.SQL)
				if *checkParse != "" && strings.Contains(c.SQL, *checkParse) {
					dumpCase(t, engine, c, got)
				}
				if !got.reject && got.detail != "" {
					t.Errorf("case %s: %s\nSQL: %s", key, got.detail, c.SQL)
					continue
				}
				agrees := got.reject == c.Reject
				if note, isTodo := meta.Todo[key]; isTodo {
					if agrees {
						t.Errorf("case %s agrees with the oracle now - remove it from todo (%s)\nSQL: %s", key, note, c.SQL)
					}
					continue
				}
				if !agrees {
					// Transformer-raised rejects: the oracle's Parser Error
					// comes from upstream's transformer, not the grammar
					// (message is not "syntax error at or near"). The
					// matcher alone cannot reject these; they are the only
					// category -record-todos will auto-record.
					transformerRaised := c.Reject && !got.reject &&
						!strings.HasPrefix(c.Error, "Parser Error: syntax error at or near")
					if *recordTodos != "" && transformerRaised {
						if meta.Todo == nil {
							meta.Todo = make(map[string]string)
						}
						meta.Todo[key] = *recordTodos
						metaDirty = true
						continue
					}
					want := "accept"
					if c.Reject {
						want = "reject (" + c.Error + ")"
					}
					gotStr := "accept"
					if got.reject {
						gotStr = "reject (" + got.detail + ")"
					}
					t.Errorf("case %s: oracle says %s, darkwing says %s\nSQL: %s", key, want, gotStr, c.SQL)
				}
			}
			if metaDirty {
				if err := testfile.WriteMetadata(path, meta); err != nil {
					t.Fatal(err)
				}
			}
		})
	}
}

func dumpCase(t *testing.T, engine *matcher.Engine, c *testfile.Case, got verdict) {
	t.Helper()
	var sb strings.Builder
	fmt.Fprintf(&sb, "case %s\nSQL: %s\noracle reject=%v %s\ndarkwing reject=%v %s\n",
		c.Key(), c.SQL, c.Reject, c.Error, got.reject, got.detail)
	tokens, err := lexer.Tokenize(c.SQL)
	if err == nil {
		sb.WriteString("tokens:\n")
		for _, tk := range tokens {
			fmt.Fprintf(&sb, "  %-16s %4d..%-4d %q\n", tk.Kind, tk.Span.Start, tk.Span.End, tk.Text)
		}
		results, err := engine.MatchAll(tokens)
		for _, result := range results {
			sb.WriteString(matcher.Dump(result))
		}
		if err != nil {
			fmt.Fprintf(&sb, "match error: %v\n", err)
		}
	}
	t.Log(sb.String())
}

// TestCorpusMetadataHygiene keeps the sidecars honest: every todo/skip key
// must refer to a case that still exists in its corpus file.
func TestCorpusMetadataHygiene(t *testing.T) {
	for _, path := range corpusFiles(t) {
		meta, err := testfile.ReadMetadata(path)
		if err != nil {
			t.Fatal(err)
		}
		if len(meta.Todo) == 0 && len(meta.Skip) == 0 {
			continue
		}
		file, err := testfile.Read(path)
		if err != nil {
			t.Fatal(err)
		}
		known := make(map[string]bool, len(file.Cases))
		for i := range file.Cases {
			known[file.Cases[i].Key()] = true
		}
		for _, m := range []map[string]string{meta.Todo, meta.Skip} {
			for _, key := range testfile.SortKeys(m) {
				if !known[key] {
					t.Errorf("%s: metadata key %s has no matching case", testfile.MetadataPath(path), key)
				}
			}
		}
	}
}

// TestCorpusRoundTrip guards the storage format: re-serializing a parsed
// corpus file must reproduce its cases exactly.
func TestCorpusRoundTrip(t *testing.T) {
	files := corpusFiles(t)
	if len(files) > 25 {
		files = files[:25]
	}
	for _, path := range files {
		file, err := testfile.Read(path)
		if err != nil {
			t.Fatal(err)
		}
		tmp := filepath.Join(t.TempDir(), "roundtrip.test")
		if err := testfile.Write(tmp, file); err != nil {
			t.Fatal(err)
		}
		again, err := testfile.Read(tmp)
		if err != nil {
			t.Fatalf("re-reading %s: %v", path, err)
		}
		if len(again.Cases) != len(file.Cases) {
			t.Fatalf("%s: round trip changed case count %d -> %d", path, len(file.Cases), len(again.Cases))
		}
		for i := range file.Cases {
			a, b := file.Cases[i], again.Cases[i]
			if a.SQL != b.SQL || a.Reject != b.Reject || a.Error != b.Error {
				t.Errorf("%s: case %d changed in round trip", path, i)
			}
		}
	}
}
